spring:
  batch:
    job:
      enabled: false
  h2:
    console: true
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:ecommerce-test
    username: sa
    password:

cart:
  job:
    max-threads: 5
    chunk-size: 2
    fixed-rate: 3000
