INSERT INTO PRODUCT (ID, VERSION, DESCRIPTION, STOCK, UNIT_PRICE) VALUES (0, 0, 'Notebook basica', 8, 7500);
INSERT INTO PRODUCT (ID, VERSION, DESCRIPTION, STOCK, UNIT_PRICE) VALUES (1, 0, 'Notebook intermedia', 5, 12000);
INSERT INTO PRODUCT (ID, VERSION, DESCRIPTION, STOCK, UNIT_PRICE) VALUES (2, 0, 'Notebook gamer', 3, 20000);
INSERT INTO PRODUCT (ID, VERSION, DESCRIPTION, STOCK, UNIT_PRICE) VALUES (3, 0, 'Cafetera express', 11, 3000);
INSERT INTO PRODUCT (ID, VERSION, DESCRIPTION, STOCK, UNIT_PRICE) VALUES (4, 0, 'Escritorio esquinero', 20, 1500);
INSERT INTO PRODUCT (ID, VERSION, DESCRIPTION, STOCK, UNIT_PRICE) VALUES (5, 0, 'Playstation 4', 15, 8000);
INSERT INTO PRODUCT (ID, VERSION, DESCRIPTION, STOCK, UNIT_PRICE) VALUES (6, 0, 'Nintendo switch', 4, 13000);